services:
  postgres:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    entrypoint: /bin/sh
    command: -c "
      until pg_isready -h postgres -p 5432; do
      echo waiting for postgres;
      sleep 2;
      done;
      migrate -path=/migrations -database=postgres://postgres:password@postgres:5432/authdb?sslmode=disable up"
    restart: "no"

volumes:
  pgdata: