CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash BYTEA NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users(email);

CREATE TABLE apps (
   id INTEGER PRIMARY KEY,
   name VARCHAR(255) NOT NULL UNIQUE,
   secret VARCHAR(255) NOT NULL UNIQUE
);
